In [1]:
import torch

In [2]:
x=torch.rand(3,3,requires_grad=True)
y=torch.rand(3,3)
print(x)
print(y)

tensor([[0.4510, 0.1256, 0.4537],
        [0.2075, 0.2681, 0.7225],
        [0.3638, 0.9234, 0.9488]], requires_grad=True)
tensor([[0.4149, 0.8449, 0.8292],
        [0.0049, 0.5694, 0.4422],
        [0.3126, 0.6823, 0.8153]])


In [4]:
#Autograd
Product=x*y
Scalar_value=Product.sum()
Scalar_value.backward()
print(x.grad)

tensor([[0.4149, 0.8449, 0.8292],
        [0.0049, 0.5694, 0.4422],
        [0.3126, 0.6823, 0.8153]])


Working of Autograd: Autograd helps to compute the gradients through a graph structure.Pytorch creates a graph with each operation represented by nodes and the entities by edges.Once the graph is computed,a forward pass takes place which finds the output.A forwrd pass is followed by a backward pass which calculates the gradient by traversing the graph in reverse order.The values of gradient are stored in the .grad attribute.

In [ ]:
#Optimizer and loss function(Adam Optimizer and MSE loss function)
import torch.nn as nn       #For neural networks
import torch.optim as optim #For optimization algorithms

model=nn.Linear(10,1)
criterion=nn.MSELoss()      #Loss function
optimizer=optim.Adam(model.parameters(),lr=0.001)

inputs=torch.randn(32,10)
targets=torch.randn(32,1)

outputs=model(inputs)
loss=criterion(outputs,targets)

optimizer.zero_grad()       #Clear previous gradients
loss.backward()             #Finds new gradients
optimizer.step()            #Updates the model 